version: "3.8"

services:
  frontend:
    build: ./streamlit_frontend
    ports:
      - "8501:8501"
    networks:
      - playdoh
    depends_on:
      - backend
    volumes:
        - ./streamlit_frontend:/app

  backend:
    build: ./fastapi_backend
    ports:
      - "8500:8001" # windows 11 tcp port 제외 범위를 피해 8500 포트 사용
    networks:
      - playdoh
    volumes:
      - ./fastapi_backend:/app
    restart: on-failure

networks:
  playdoh:
    driver: bridge
    