version: "3.8"

services:
  frontend:
    build: ./streamlit_frontend
    ports:
      - "80:8501"
    networks:
      - playdoh
    depends_on:
      - backend
    volumes:
        - ./streamlit_frontend:/app
    restart: always

  backend:
    build: ./fastapi_backend
    ports: 
      - "8001"
    networks:
      - playdoh
    volumes:
      - ./fastapi_backend:/app
    restart: always

networks:
  playdoh:
    driver: bridge